import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Exo} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/navbar/Navbar";
import ToastProvider from "@/components/ToastProvider/ToastProvider";
import Mysession from "@/components/MySession/Mysession";
import Footer from "@/components/Footer/Footer";

const inter = Exo({subsets:['latin'],variable:'--font-sans'});



export const metadata: Metadata = {
  title: "FreshCart",
  description: "Generated by yousif mostafa",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html
      lang="en"
      className={cn( "antialiased", "font-sans", inter.variable)}
    >
      <body className="min-h-full flex flex-col">
    <Mysession>
   <Navbar/>
        {children}
          <ToastProvider />
<Footer/>
    </Mysession>
     

        </body>
    </html>
  );
}
